config/routes.rb
Rails.application.routes.draw do

resources :to_dos

# get "todos" to: "todos#index"
# #lire tous les todo

# get "todos/:id" to: "todos#shows"
# #lire 1 todo

# get "todos/new" to: "todos#new"
# post "todos" to: "todos#create"
# #créer une todo

# get "todos/:id/edit" => "todos#edit"
# patch "todos/:id", to: "todos#update"
# #modifier une todo

# delete  "todos/:id", to: "todos#destroy"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/to_do.rb
class ToDo < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/to_dos_controller.rb
class ToDosController < ApplicationController

  before_action :set_todo, only: [:show, :edit, :update, :destroy]
  def index         # GET /todos
    @todos = ToDo.all
  end

  def show          # GET /todos/:id
  end

  def new           # GET /todos/new
    @todo = ToDo.new
  end

  def create        # POST /todos
    @todo = ToDo.new(todo_params)
    @todo.save
    redirect_to to_do_path(@todo)
  end

  def edit          # GET /todos/:id/edit
  end

  def update        # PATCH /todos/:id
    @todo.update(todo_params)
    redirect_to to_do_path(@todo)
  end

  def destroy       # DELETE /todos/:id
    @todo.destroy
    redirect_to to_dos_path
  end

  private

  def set_todo
    @todo = ToDo.find(params[:id])
  end

  def todo_params
    params.require(:to_do).permit(:task,:time)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/to_dos/_form.html.erb
<%= form_for(@todo) do |f| %>
  <%= f.label :task %>
  <%= f.text_field :task %>

  <%= f.label :time %>
  <%= f.text_field :time %>

  <%= f.submit %>
<% end %>

app/views/to_dos/edit.html.erb
<%= render "form" %>

app/views/to_dos/index.html.erb
<h1>All the Todos</h1>


<%= link_to "create new", new_to_do_path %>
<% @todos.each do |todo| %>
<h2><%= todo.task %></h2>
<h3><%= todo.time %></h3>
<%= link_to "Edit", edit_to_do_path(todo) %>
<%= link_to "Show", to_do_path(todo) %>
<%= link_to "Delete", to_do_path(todo),
      method: :delete,
      data: { confirm: "Are you sure?" } %>
<% end %>

app/views/to_dos/new.html.erb
<%= render "form" %>

app/views/to_dos/show.html.erb
<h2><%= @todo.task %></h2>
<p><%= @todo.time %></p>